%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
CameraMat: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [768.416941, -0.303774,  1206.804108,
         0.0,        768.240854, 993.276818,
         0.0,        0.0,        1.0     ]

DistCoeffs: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [0.017931, 0.006102, -0.10670, -0.010670, 0.000000]

Camera.width: 2448
Camera.height: 2048
