%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
CameraMat: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [592.31954,   0.     , 297.83982,
           0.     , 594.89289, 248.34304,
           0.     ,   0.     ,   1.     ]

DistCoeffs: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [-0.103009, 0.105492, 0.001131, -0.000095, 0.000000]

Camera.width: 610
Camera.height: 512
