camera_count : 4

camera1:
    name: cam1
    serial_number: 40097766


camera2:
    name: cam2
    serial_number: 40097767

camera3:
    name: cam3
    serial_number: 40097977


camera4:
    name: cam4
    serial_number: 40097973

